### ISSUE TITLE
Unsure if gc11_check_trail_logging is working as intended (please confirm)

### ISSUE THREAD

**Issue by tuningdipsw** [ssc-spc-ccoe-cei/aws-guardrails-cac-solution#159]
**Description of the bug/Issue**
gc11_c_t_l is reporting noncompliant for standard LZA installation's config. (More detail below)

**Resources that are affected**
Cloudtrails

**Current behavior**
Standard LZA installation config (CCCS medium) has
```
logging:
  account: LogArchive
  cloudtrail:
    enable: true
    organizationTrail: true
    organizationTrailSettings:
      ...
      managementEvents: true
      s3DataEvents: true

[and the same for accountTrails]
```

This creates a CloudTrail in every account with two event selectors:
1. Management events. This is fine by CaC
2. Data events (s3 buckets). This selector does not have mgmt events enabled, so gc11_c_t_l marks the CloudTrail as non-compliant.

I would like to confirm if this behavior is intended.

**To Reproduce**
Install LZA on AWS for CCCS medium with default configuration.
Install CaC solution.

**Expected behavior**
Please clarify whether the requirement that separate data event selectors also log management events is intended, or if the requirement is that every CloudTrail should have (at least) 1 event selector that logs management events.

If it is intended, it would be helpful if the note in the Remediation guide for GC 11.2 could be updated to clarify that LZA installations require some additional work to comply with the check.

**Additional context**
SSC AWS CaC v2.0.4
LZA config CCCS medium v1.11.2-a
